// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtMF08QpkhNvJqhuzKvnIixoXttaUYjDQ',
    appId: '1:137654306991:web:3e91eeb6890a5ff2446c5a',
    messagingSenderId: '137654306991',
    projectId: 'newmessenger-98aed',
    authDomain: 'newmessenger-98aed.firebaseapp.com',
    storageBucket: 'newmessenger-98aed.appspot.com',
    measurementId: 'G-2KLXF9E13E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJJs1RY5erfIplbIJAxvV_jqErP0oB-aE',
    appId: '1:137654306991:android:24f509ba8f13cae5446c5a',
    messagingSenderId: '137654306991',
    projectId: 'newmessenger-98aed',
    storageBucket: 'newmessenger-98aed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlu5Yr1HFqhs19bqARev6BKOhko6MzGQ8',
    appId: '1:137654306991:ios:43c610f0fb03c541446c5a',
    messagingSenderId: '137654306991',
    projectId: 'newmessenger-98aed',
    storageBucket: 'newmessenger-98aed.appspot.com',
    iosClientId: '137654306991-0v01fdln7jjhl53jc958hep27pkt5sli.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerClone',
  );
}
